## Full Data Cleaning

**Notes**
* Data cleaning follows the same logic as shown in initial.ipynb
* This notebook will also contain yearly data from the 2012-2013 school year through the 2021-2022 school year.

In [383]:
import numpy as np
import pandas as pd
import os
from functools import reduce

In [384]:
dfs = []

for file in os.listdir('./data'):
    if file.endswith(('.xls', '.xlsx')):
        print('Parsing', file)
        df = pd.read_excel(f'./data/{file}', skiprows=1)
        df['Year'] = file.split('.')[0]
        dfs.append(df)

data = pd.concat(dfs, ignore_index=True)

Parsing enroll2016-17.xls
Parsing enroll2014-15.xls
Parsing enroll2012-13.xls
Parsing enroll2021-22.xlsx
Parsing enroll2019-20.xls
Parsing enroll2017-18.xls
Parsing enroll2015-16.xls
Parsing enroll2020-21.xls
Parsing enroll2018-19.xls
Parsing enroll2013-14.xls

In [385]:
data.head()

,State or jurisdiction,Public,Unnamed: 2,Unnamed: 3,Unnamed: 4,Private,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Public.1,Public.2,Public.3,Private.1,Private.2,Private.3,Private.4,Private.5,Private.6,Private.7
0,NaN,Undergraduate,NaN,NaN,Post- bacca- laureate,Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,4-year,2-year,NaN,Total,Nonprofit 4-year,For-profit 4-year,Nonprofit 2-year,For-profit 2-year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States ........,13141086,7300010,5841076,1441886,3728126,2762212,716745,50557,198612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alabama ....................,216115,135080,81035,34923,41893,19891,19627,386,1989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [386]:
data.head(5).T

,0,1,2,3,4
State or jurisdiction,NaN,NaN,1,United States ........,Alabama ....................
Public,Undergraduate,Total,2,13141086,216115
Unnamed: 2,NaN,4-year,3,7300010,135080
Unnamed: 3,NaN,2-year,4,5841076,81035
Unnamed: 4,Post- bacca- laureate,NaN,5,1441886,34923
Private,Undergraduate,Total,6,3728126,41893
Unnamed: 6,NaN,Nonprofit 4-year,7,2762212,19891
Unnamed: 7,NaN,For-profit 4-year,8,716745,19627
Unnamed: 8,NaN,Nonprofit 2-year,9,50557,386
Unnamed: 9,NaN,For-profit 2-year,10,198612,1989
Unnamed: 10,Postbaccalaureate,Total,11,1529916,11121
Unnamed: 11,NaN,Nonprofit 4-year,12,1265028,4679
Unnamed: 12,NaN,For-profit 4-year,13,264888,6442
Unnamed: 13,NaN,NaN,NaN,NaN,NaN
Year,enroll2016-17,enroll2016-17,enroll2016-17,enroll2016-17,enroll2016-17
Public.1,NaN,NaN,NaN,NaN,NaN
Public.2,NaN,NaN,NaN,NaN,NaN
Public.3,NaN,NaN,NaN,NaN,NaN
Private.1,NaN,NaN,NaN,NaN,NaN
Private.2,NaN,NaN,NaN,NaN,NaN
Private.3,NaN,NaN,NaN,NaN,NaN
Private.4,NaN,NaN,NaN,NaN,NaN
Private.5,NaN,NaN,NaN,NaN,NaN
Private.6,NaN,NaN,NaN,NaN,NaN
Private.7,NaN,NaN,NaN,NaN,NaN

In [387]:
data['Year'] = data['Year'].str.replace('enroll', '')
data['State or jurisdiction'] = data['State or jurisdiction'].str.replace(r'\.+$', '', regex=True).str.strip()

In [388]:
data.head()

,State or jurisdiction,Public,Unnamed: 2,Unnamed: 3,Unnamed: 4,Private,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Public.1,Public.2,Public.3,Private.1,Private.2,Private.3,Private.4,Private.5,Private.6,Private.7
0,NaN,Undergraduate,NaN,NaN,Post- bacca- laureate,Undergraduate,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,4-year,2-year,NaN,Total,Nonprofit 4-year,For-profit 4-year,Nonprofit 2-year,For-profit 2-year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2,3,4,5,6,7,8,9,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States,13141086,7300010,5841076,1441886,3728126,2762212,716745,50557,198612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alabama,216115,135080,81035,34923,41893,19891,19627,386,1989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [389]:
df21 = data[data['Year'] == '2021-22']
df21 = df21[[ 'State or jurisdiction', 'Year','Public', 'Public.1',
'Public.2',
'Public.3',
'Private',
'Private.1',
'Private.2',
'Private.3',
'Private.4',
'Private.5',
'Private.6',
'Private.7']
]
df21
df21.columns = ['State or jurisdiction', 'Year', 'Total_ug', '4-year', '2-year',
       'Total_pb', 'Total_pug', 'Nonprofit 4-year_x', 'For-profit 4-year_x',
       'Nonprofit 2-year', 'For-profit 2-year', 'Total_ppb',
       'Nonprofit 4-year_y', 'For-profit 4-year_y']

In [390]:
df21.dropna(inplace=True)
df21 = df21.drop([264, 265])
df21

,State or jurisdiction,Year,Total_ug,4-year,2-year,Total_pb,Total_pug,Nonprofit 4-year_x,For-profit 4-year_x,Nonprofit 2-year,For-profit 2-year,Total_ppb,Nonprofit 4-year_y,For-profit 4-year_y
267,United States,2021-22,11944633,7466861,4477772,1598891,3503787,2698780,600183,27574,177250,1612540,1386750,225790
268,Alabama,2021-22,207241,131801,75440,42939,32151,18116,13201,295,539,10429,5478,4951
269,Alaska,2021-22,18128,18128,†,1808,815,420,†,78,317,178,178,†
270,Arizona,2021-22,322815,170336,152479,43693,179110,5802,159804,†,13504,68528,6154,62374
271,Arkansas,2021-22,112180,72905,39275,18970,13785,12438,355,977,15,2821,2774,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,Marshall Islands,2021-22,1267,1267,†,†,†,†,†,†,†,†,†,†
325,Northern Marianas,2021-22,1298,1298,†,†,†,†,†,†,†,†,†,†
326,Palau,2021-22,525,†,525,†,†,†,†,†,†,†,†,†
327,Puerto Rico,2021-22,43351,42409,942,5748,98665,67328,27089,†,4248,20536,17419,3117
328,U.S. Virgin Islands,2021-22,1374,1374,†,250,†,†,†,†,†,†,†,†

In [391]:
public_undergrad = data[['State or jurisdiction','Year', 'Public', 'Unnamed: 2', 'Unnamed: 3']]
public_undergrad = public_undergrad.drop([0,1,2])
public_undergrad.columns = ['State or jurisdiction', 'Year', 'Total_ug','4-year', '2-year'] 
public_undergrad.dropna(inplace=True)
public_undergrad

    State or jurisdiction     Year  Total_ug   4-year   2-year
3           United States  2016-17  13141086  7300010  5841076
4                 Alabama  2016-17    216115   135080    81035
5                  Alaska  2016-17     25146    24958      188
6                 Arizona  2016-17    329282   141410   187872
7                Arkansas  2016-17    130299    81842    48457
..                    ...      ...       ...      ...      ...
810      Marshall Islands  2013-14      1000        0     1000
811     Northern Marianas  2013-14      1109     1109        0
812                 Palau  2013-14       646        0      646
813           Puerto Rico  2013-14     56617    53707     2910
814   U.S. Virgin Islands  2013-14      2143     2143        0

[558 rows x 5 columns]

In [392]:
public_pb = data[['State or jurisdiction','Year', 'Unnamed: 4']]
public_pb = public_pb.drop([0,1,2])
public_pb.columns = ['State or jurisdiction', 'Year', 'Total_pb']
public_pb.dropna(inplace=True)
public_pb

    State or jurisdiction     Year Total_pb
3           United States  2016-17  1441886
4                 Alabama  2016-17    34923
5                  Alaska  2016-17     2206
6                 Arizona  2016-17    32118
7                Arkansas  2016-17    19084
..                    ...      ...      ...
810      Marshall Islands  2013-14        0
811     Northern Marianas  2013-14        0
812                 Palau  2013-14        0
813           Puerto Rico  2013-14     6070
814   U.S. Virgin Islands  2013-14      178

[558 rows x 3 columns]

In [393]:
private_undergrad = data[['State or jurisdiction','Year','Private' ] + [name for name in data.columns if name.startswith('Unnamed') and name.endswith(('6', '7', '8', '9'))]]
private_undergrad = private_undergrad.drop([0,1,2])
private_undergrad.columns = ['State or jurisdiction', 'Year', 'Total_pug', 'Nonprofit 4-year', 'For-profit 4-year', 'Nonprofit 2-year', 'For-profit 2-year']
private_undergrad.dropna(inplace=True)
private_undergrad

,State or jurisdiction,Year,Total_pug,Nonprofit 4-year,For-profit 4-year,Nonprofit 2-year,For-profit 2-year
3,United States,2016-17,3728126,2762212,716745,50557,198612
4,Alabama,2016-17,41893,19891,19627,386,1989
5,Alaska,2016-17,851,348,0,79,424
6,Arizona,2016-17,181083,4928,166124,0,10031
7,Arkansas,2016-17,15661,14085,279,1178,119
...,...,...,...,...,...,...,...
810,Marshall Islands,2013-14,0,0,0,0,0
811,Northern Marianas,2013-14,0,0,0,0,0
812,Palau,2013-14,0,0,0,0,0
813,Puerto Rico,2013-14,154493,113510,13086,0,27897
814,U.S. Virgin Islands,2013-14,0,0,0,0,0

In [394]:
private_pb = data[['State or jurisdiction', 'Year', ] + [name for name in data.columns if name.startswith('Unnamed') and name.endswith(('10', '11', '12'))]]
private_pb = private_pb.drop([0,1])
private_pb.columns = ['State or jurisdiction', 'Year', 'Total_ppb', 'Nonprofit 4-year', 'For-profit 4-year']
private_pb.dropna(inplace=True)
private_pb

,State or jurisdiction,Year,Total_ppb,Nonprofit 4-year,For-profit 4-year
3,United States,2016-17,1529916,1265028,264888
4,Alabama,2016-17,11121,4679,6442
5,Alaska,2016-17,243,243,0
6,Arizona,2016-17,65601,4872,60729
7,Arkansas,2016-17,2276,2183,93
...,...,...,...,...,...
810,Marshall Islands,2013-14,0,0,0
811,Northern Marianas,2013-14,0,0,0
812,Palau,2013-14,0,0,0
813,Puerto Rico,2013-14,21835,20998,837
814,U.S. Virgin Islands,2013-14,0,0,0

In [395]:
for df in [public_pb, private_pb, public_undergrad, private_undergrad, df21]:
    df.replace('†', 0, inplace=True)
    df = df.reset_index(drop=True, inplace=True)

/var/folders/6g/_wpr8bs53rs84lqb6nn_rk900000gn/T/ipykernel_56683/3438375672.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('†', 0, inplace=True)

In [396]:
dfs = [public_undergrad, public_pb, private_undergrad, private_pb]

merged_df = reduce(
    lambda left, right: pd.merge(left, right, on=('State or jurisdiction','Year'), how='outer'),
    dfs
)

In [397]:
merged_df['Year'].value_counts()

Year
2012-13    62
2013-14    62
2014-15    62
2015-16    62
2016-17    62
2017-18    62
2018-19    62
2019-20    62
2020-21    62
Name: count, dtype: int64

In [398]:
merged_df

,State or jurisdiction,Year,Total_ug,4-year,2-year,Total_pb,Total_pug,Nonprofit 4-year_x,For-profit 4-year_x,Nonprofit 2-year,For-profit 2-year,Total_ppb,Nonprofit 4-year_y,For-profit 4-year_y
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,Wyoming,2016-17,30224,9788,20436,2578,563,45,0,518,0,0,0,0
554,Wyoming,2017-18,29945,9791,20154,2606,464,0,0,464,0,0,0,0
555,Wyoming,2018-19,30020,9998,20022,2452,38,0,0,0,38,0,0,0
556,Wyoming,2019-20,29678,9807,19871,2442,253,0,0,0,253,0,0,0
557,Wyoming,2020-21,27871,14935,12936,2487,585,0,0,0,585,0,0,0

In [399]:
merged_df.columns

Index(['State or jurisdiction', 'Year', 'Total_ug', '4-year', '2-year',
       'Total_pb', 'Total_pug', 'Nonprofit 4-year_x', 'For-profit 4-year_x',
       'Nonprofit 2-year', 'For-profit 2-year', 'Total_ppb',
       'Nonprofit 4-year_y', 'For-profit 4-year_y'],
      dtype='object')

In [400]:
print(len(df21))
print(len(merged_df))

62
558

In [401]:
merged_df = pd.concat([merged_df, df21])
merged_df.reset_index(drop=True, inplace=True)

In [402]:
merged_df.columns = [
    'State or jurisdiction',
    'Year',
    'Total_Pub_Under', 
    '4y_Pub_Under', 
    '2y_Pub_Under', ''
    'Total_Pub_Postbacc',
    'Total_Priv_Under',
    'Np_4y_Priv_Under',
    'Fp_4y_Priv_Under',
    'Np_2y_Priv_Under',
    'Fp_2y_Priv_Under',
    'Total_Priv_Postbacc',
    'Np_4y_Priv_Postbacc',
    'Fp_4y_Priv_Postbacc'
    ]

In [403]:
merged_df

,State or jurisdiction,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Marshall Islands,2021-22,1267,1267,0,0,0,0,0,0,0,0,0,0
616,Northern Marianas,2021-22,1298,1298,0,0,0,0,0,0,0,0,0,0
617,Palau,2021-22,525,0,525,0,0,0,0,0,0,0,0,0
618,Puerto Rico,2021-22,43351,42409,942,5748,98665,67328,27089,0,4248,20536,17419,3117
619,U.S. Virgin Islands,2021-22,1374,1374,0,250,0,0,0,0,0,0,0,0

In [404]:
merged_df[merged_df['Year'] == '2021-22']

,State or jurisdiction,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc
558,United States,2021-22,11944633,7466861,4477772,1598891,3503787,2698780,600183,27574,177250,1612540,1386750,225790
559,Alabama,2021-22,207241,131801,75440,42939,32151,18116,13201,295,539,10429,5478,4951
560,Alaska,2021-22,18128,18128,0,1808,815,420,0,78,317,178,178,0
561,Arizona,2021-22,322815,170336,152479,43693,179110,5802,159804,0,13504,68528,6154,62374
562,Arkansas,2021-22,112180,72905,39275,18970,13785,12438,355,977,15,2821,2774,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Marshall Islands,2021-22,1267,1267,0,0,0,0,0,0,0,0,0,0
616,Northern Marianas,2021-22,1298,1298,0,0,0,0,0,0,0,0,0,0
617,Palau,2021-22,525,0,525,0,0,0,0,0,0,0,0,0
618,Puerto Rico,2021-22,43351,42409,942,5748,98665,67328,27089,0,4248,20536,17419,3117
619,U.S. Virgin Islands,2021-22,1374,1374,0,250,0,0,0,0,0,0,0,0

In [405]:
merged_df.to_csv('./data/cleaned_enrollmentdata.csv', index=False)