## Geographic Analysis

Do enrollment trends cluster geographically, and what regional patterns emerge?

In [45]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
from scipy import stats

In [46]:
enroll_df = pd.read_csv(os.path.dirname(os.getcwd()) + '/data/cleaned_enrollmentdata.csv')

In [47]:
enroll_df.rename(columns={'State or jurisdiction': 'State'}, inplace=True)
enroll_df.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442

In [48]:
states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut",
    "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan",
    "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire",
    "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia",
    "Wisconsin", "Wyoming", "District of Columbia"
]

state_enrollment = enroll_df[enroll_df["State"].isin(states)]
state_enrollment['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [49]:
state_enrollment = state_enrollment.copy()
state_enrollment['Total_Enrollment'] = state_enrollment['Total_Pub_Under'] + state_enrollment['Total_Priv_Under']
state_enrollment.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967,265917
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043,261188
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513,259630
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233,257650
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442,258008

In [50]:
northeast = [
    "Connecticut", "Maine", "Massachusetts", "New Hampshire",
    "New Jersey", "New York", "Pennsylvania", "Rhode Island", "Vermont"
]

midwest = [
    "Illinois", "Indiana", "Iowa", "Kansas", "Michigan", "Minnesota",
    "Missouri", "Nebraska", "North Dakota", "Ohio", "South Dakota",
    "Wisconsin"
]

south = [
    "Alabama", "Arkansas", "Delaware", "Florida", "Georgia", "Kentucky",
    "Louisiana", "Maryland", "Mississippi", "North Carolina", "Oklahoma",
    "South Carolina", "Tennessee", "Texas", "Virginia", "West Virginia"
]

west = [
    "Alaska", "Arizona", "California", "Colorado", "Hawaii", "Idaho",
    "Montana", "Nevada", "New Mexico", "Oregon", "Utah", "Washington",
    "Wyoming"
]

In [51]:
regions = {
    "Northeast": northeast,
    "Midwest": midwest,
    "South": south,
    "West": west
}

In [52]:
northeast_enrollment = state_enrollment[state_enrollment["State"].isin(northeast)]
northeast_enrollment.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
63,Connecticut,2012-13,111481,53253,58228,13471,55331,47176,7883,0,272,21375,20589,786,166812
64,Connecticut,2013-14,109851,52874,56977,13242,56330,47885,8383,0,62,21543,20832,711,166181
65,Connecticut,2014-15,108641,53487,55154,13662,57184,48679,8505,0,0,22441,21717,724,165825
66,Connecticut,2015-16,106337,53576,52761,13429,56722,49154,7568,0,0,23178,22561,617,163059
67,Connecticut,2016-17,103564,53016,50548,13781,57088,49388,7700,0,0,23578,22956,622,160652

In [53]:
southern_enrollment = state_enrollment[state_enrollment["State"].isin(south)]
southern_enrollment.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967,265917
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043,261188
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513,259630
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233,257650
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442,258008

In [54]:
midwest_enrollment = state_enrollment[state_enrollment["State"].isin(midwest)]
midwest_enrollment.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
144,Illinois,2012-13,507197,148467,358730,49940,206514,137447,60339,718,8010,103459,89662,13797,713711
145,Illinois,2013-14,496801,145231,351570,49682,197298,136856,53879,743,5820,99107,86528,12579,694099
146,Illinois,2014-15,480483,144381,336102,48979,195768,136222,53353,735,5458,99750,85694,14056,676251
147,Illinois,2015-16,459770,143615,316155,49334,190820,134754,49923,389,5754,102319,86199,16120,650590
148,Illinois,2016-17,443681,139508,304173,48897,182387,131672,45300,368,5047,102755,86243,16512,626068

In [55]:
western_enrollment = state_enrollment[state_enrollment["State"].isin(west)]
western_enrollment.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
9,Alaska,2012-13,28034,27276,758,2561,1984,497,1259,0,228,218,218,0,30018
10,Alaska,2013-14,29089,27014,2075,2511,3008,429,2191,53,335,282,282,0,32097
11,Alaska,2014-15,27588,26456,1132,2304,4175,372,3256,68,479,264,253,11,31763
12,Alaska,2015-16,26118,25925,193,2275,2694,315,1935,66,378,244,234,10,28812
13,Alaska,2016-17,25146,24958,188,2206,851,348,0,79,424,243,243,0,25997

**sub-question:** Are Northeastern states experiencing different trends than Southern/Western states?

In [56]:
ne_year_trends = northeast_enrollment.groupby("Year").agg({"Total_Enrollment": "sum"}).reset_index()
ne_year_trends.head()

      Year  Total_Enrollment
0  2012-13           2877934
1  2013-14           2862350
2  2014-15           2852403
3  2015-16           2813510
4  2016-17           2780728

In [57]:
s_year_trends = southern_enrollment.groupby("Year").agg({"Total_Enrollment": "sum"}).reset_index()
s_year_trends.head()

      Year  Total_Enrollment
0  2012-13           6133962
1  2013-14           6036847
2  2014-15           5976291
3  2015-16           5906797
4  2016-17           5892357

In [58]:
w_year_trends = western_enrollment.groupby("Year").agg({"Total_Enrollment": "sum"}).reset_index()
w_year_trends.head()

      Year  Total_Enrollment
0  2012-13           4611684
1  2013-14           4562435
2  2014-15           4595443
3  2015-16           4552909
4  2016-17           4527540

In [62]:
fig = go.Figure()

# Northeast
fig.add_trace(go.Scatter(
    x=ne_year_trends['Year'],
    y=ne_year_trends['Total_Enrollment'],
    mode='lines+markers',
    name='Northeast'
))

# Southeast
fig.add_trace(go.Scatter(
    x=s_year_trends['Year'],
    y=s_year_trends['Total_Enrollment'],
    mode='lines+markers',
    name='Southeast'
))

# West
fig.add_trace(go.Scatter(
    x=w_year_trends['Year'],
    y=w_year_trends['Total_Enrollment'],
    mode='lines+markers',
    name='West'
))

fig.update_layout(
    title="Total Enrollment by Region",
    xaxis_title="Year",
    yaxis_title="Total Enrollment",
    legend_title="Region"
)

fig.show()

**sub-question:** Is there spatial autocorrelation in enrollment trends? (Do neighboring states behave similarly?)

**sub-question:** Are urban vs rural states showing different patterns?

**sub-question:** Which Census regions/divisions show the strongest declines?