## Project Restructure: Descriptive Analysis

**Notes**
3 Main areas of analysis:
 * Temporal
 * Institutional
 * Geographic

Did not include all territories and jurisdictions that analysis will be done separately. Focusing solely on the U.S. states.

## Temporal Analysis

**Question**
How has undergraduate enrollment changed across U.S. states from 2012-2022, and are these changes statistically significant?

In [199]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import t
import plotly.express as px
import plotly.graph_objects as go
import os

In [200]:
enrollment_df = pd.read_csv(os.path.dirname(os.getcwd()) + '/data/cleaned_enrollmentdata.csv')
enrollment_df.rename(columns={'State or jurisdiction': 'State'}, inplace=True)
enrollment_df.head()

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442

In [201]:
states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut",
    "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan",
    "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire",
    "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia",
    "Wisconsin", "Wyoming", "District of Columbia"
]

state_enrollment = enrollment_df[enrollment_df["State"].isin(states)]
state_enrollment['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

--------

**Sub-Question** What is the national enrollment trend when aggregating across all states?

In [202]:
state_enrollment['Total_Enrollment'] = state_enrollment['Total_Pub_Under'] + state_enrollment['Total_Priv_Under']
state_enrollment.head()

/var/folders/6g/_wpr8bs53rs84lqb6nn_rk900000gn/T/ipykernel_48341/1575148348.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,State,Year,Total_Pub_Under,4y_Pub_Under,2y_Pub_Under,Total_Pub_Postbacc,Total_Priv_Under,Np_4y_Priv_Under,Fp_4y_Priv_Under,Np_2y_Priv_Under,Fp_2y_Priv_Under,Total_Priv_Postbacc,Np_4y_Priv_Postbacc,Fp_4y_Priv_Postbacc,Total_Enrollment
0,Alabama,2012-13,216535,130260,86275,34510,49382,21674,24045,518,3145,9884,3917,5967,265917
1,Alabama,2013-14,213669,129045,84624,34615,47519,20808,23295,472,2944,9909,3866,6043,261188
2,Alabama,2014-15,212458,129916,82542,34531,47172,21160,22714,518,2780,10867,4354,6513,259630
3,Alabama,2015-16,212968,131503,81465,34483,44682,20938,21000,436,2308,10826,4593,6233,257650
4,Alabama,2016-17,216115,135080,81035,34923,41893,19891,19627,386,1989,11121,4679,6442,258008

In [203]:
nationwide_trends = state_enrollment.groupby('Year').agg({'Total_Enrollment': 'sum', 'Total_Pub_Under': 'sum', 'Total_Priv_Under': 'sum'}).reset_index()
nationwide_trends

      Year  Total_Enrollment  Total_Pub_Under  Total_Priv_Under
0  2012-13          17717229         13458541           4258688
1  2013-14          17459865         13332032           4127833
2  2014-15          17278075         13230125           4047950
3  2015-16          17021992         13130934           3891058
4  2016-17          16854168         13126042           3728126
5  2017-18          16745071         13085693           3659378
6  2018-19          16594731         13033822           3560909
7  2019-20          16549691         12986168           3563523
8  2020-21          15836385         12305625           3530760
9  2021-22          15433062         11929275           3503787

In [204]:
baseline_year = nationwide_trends[nationwide_trends['Year'] == '2012-13']
baseline_enrollment = nationwide_trends['Total_Enrollment'][0]
nationwide_trends['enrollment_index'] = (nationwide_trends['Total_Enrollment'] / baseline_enrollment) * 100
nationwide_trends['yoy_change'] = nationwide_trends['Total_Enrollment'].pct_change() * 100

In [205]:
total_change_pct = ((nationwide_trends['Total_Enrollment'][9] - nationwide_trends['Total_Enrollment'][0])/baseline_enrollment) * 100
print(total_change_pct)

-12.892349023653754

In [206]:
years = np.arange(len(nationwide_trends))
slope,intercept, r_value, p_value, std_err = stats.linregress(years, nationwide_trends['enrollment_index'])

In [207]:
n = len(years)
dof = n - 2
t_crit = t.ppf(0.975, dof)  # 95% CI
ci_slope = t_crit * std_err

In [208]:
print('Baseline: ', baseline_enrollment)
print('2021-22: ', nationwide_trends['Total_Enrollment'][9])
print('Total Change %: ', total_change_pct)
print('Avg Change %: ', nationwide_trends['yoy_change'].mean())
print('Slope: ', slope)
print('Intercept: ', intercept)
print('95% CI: ', ci_slope)
print('R Squared: ', r_value**2)
print('P-Value: ', p_value)

Baseline:  17717229
2021-22:  15433062
Total Change %:  -12.892349023653754
Avg Change %:  -1.5150317578493226
Slope:  -1.2641234955277412
Intercept:  100.22380669942542
95% CI:  0.2766016400003222
R Squared:  0.9328116061637491
P-Value:  5.728672704293977e-06

P-Value is much less than the alpha value of 0.05, this means that the national enrollment trend is statistically significant.

### Visualization

In [209]:
## Enrollment Over time
px.line(nationwide_trends, x='Year', y='Total_Enrollment')

In [210]:
## YoY Change Over time
px.line(nationwide_trends, x='Year', y='yoy_change')

In [211]:
## Statistical Predictions
fig = go.Figure()

fig.add_trace(go.Scatter(
    x = nationwide_trends['Year'],
    y = nationwide_trends['enrollment_index'],
    mode = 'lines',
    name = 'Enrollment Index'
))

predictions = slope * years + intercept
fig.add_trace(go.Scatter(
    x=nationwide_trends['Year'],
    y=predictions,
    mode='lines',
    name=f'Linear Trend (R_squared={r_value**2:.3f})',
    line=dict(color='red', width=2, dash='dash')
))

fig.update_layout(
    title='Enrollment Index Over Time',
    xaxis_title='Year',
    yaxis_title='Enrollment Index',
    showlegend=True
)


fig.show()

Baseline is at 100. We see a clear downward trend of enrollment. The linear regression easily captures 93 % of the variance.

**Question** What is the national enrollment trend when aggregating across all states?

**Answer** There is a negative enrollment trend when aggregfating across all the states.

---------

**Question** Which states have statistically significant declining trends?

In [212]:
state_trends = state_enrollment.groupby(['State', 'Year']).agg({'Total_Enrollment': 'sum', 'Total_Pub_Under': 'sum', 'Total_Priv_Under': 'sum'}).reset_index()
state_trends

       State     Year  Total_Enrollment  Total_Pub_Under  Total_Priv_Under
0    Alabama  2012-13            265917           216535             49382
1    Alabama  2013-14            261188           213669             47519
2    Alabama  2014-15            259630           212458             47172
3    Alabama  2015-16            257650           212968             44682
4    Alabama  2016-17            258008           216115             41893
..       ...      ...               ...              ...               ...
505  Wyoming  2017-18             30409            29945               464
506  Wyoming  2018-19             30058            30020                38
507  Wyoming  2019-20             29931            29678               253
508  Wyoming  2020-21             28456            27871               585
509  Wyoming  2021-22             27837            27095               742

[510 rows x 5 columns]

In [213]:
states = state_enrollment['State'].unique()

total_change_pct_dict = {state: [] for state in states}
baseline_enrollment_dict = {state: [] for state in states}

for state in states:
    mask = state_trends['State'] == state
    df = state_trends[state_trends['State'] == state].copy()
    year_baseline = '2012-13'
    state_baseline = df[df['Year'] == year_baseline]['Total_Enrollment'].values[0]
    baseline_enrollment_dict[state].append(state_baseline)
    total_change_pct_dict[state].append(((state_trends[state_trends['State'] == state]['Total_Enrollment'].values[9] - state_trends[state_trends['State'] == state]['Total_Enrollment'].values[0])/state_baseline) * 100)
    df['enrollment_index'] = (df['Total_Enrollment'] / state_baseline) * 100
    df['yoy_change'] = df['Total_Enrollment'].pct_change() * 100
    state_trends.loc[mask, 'enrollment_index'] = df['enrollment_index']
    state_trends.loc[mask, 'yoy_change'] = df['yoy_change']

state_trends

,State,Year,Total_Enrollment,Total_Pub_Under,Total_Priv_Under,enrollment_index,yoy_change
0,Alabama,2012-13,265917,216535,49382,100.000000,NaN
1,Alabama,2013-14,261188,213669,47519,98.221626,-1.778374
2,Alabama,2014-15,259630,212458,47172,97.635728,-0.596505
3,Alabama,2015-16,257650,212968,44682,96.891135,-0.762624
4,Alabama,2016-17,258008,216115,41893,97.025764,0.138948
...,...,...,...,...,...,...,...
505,Wyoming,2017-18,30409,29945,464,86.627924,-1.227791
506,Wyoming,2018-19,30058,30020,38,85.628009,-1.154264
507,Wyoming,2019-20,29931,29678,253,85.266217,-0.422516
508,Wyoming,2020-21,28456,27871,585,81.064296,-4.928001
509,Wyoming,2021-22,27837,27095,742,79.300914,-2.175288

In [214]:
avg_change_pct_dict = {state: [] for state in states}
slope_dict = {state: [] for state in states}
intercept_dict = {state: [] for state in states}
ci_slope_dict = {state: [] for state in states}
r_squared_dict = {state: [] for state in states}
p_value_dict = {state: [] for state in states}


state_years = np.arange(len(state_trends[state_trends['State'] == 'Alabama']))

for state in states:
    slope,intercept, r_value, p_value, std_err = stats.linregress(state_years, state_trends[state_trends['State'] == state]['enrollment_index'])
    ci_slope = t.interval(0.95, len(state_years)-1, loc=slope, scale=std_err)
    slope_dict[state].append(slope)
    intercept_dict[state].append(intercept)
    ci_slope_dict[state].append(ci_slope)
    r_squared_dict[state].append(r_value**2)
    p_value_dict[state].append(p_value)
    avg_change_pct_dict[state].append(state_trends[state_trends['State'] == state]['yoy_change'].mean())

In [215]:
significant = []
insignificant = []
for state in states:
    print("STATE: ", state)
    print('Baseline: ', baseline_enrollment_dict.get(state)[0])
    print('2021-22: ', state_trends[state_trends['State'] == state]['Total_Enrollment'].values[9])
    print('Total Change %: ', total_change_pct_dict[state])
    print('Avg Change %: ', avg_change_pct_dict.get(state)[0])
    print('Slope: ', slope_dict.get(state)[0])
    print('Intercept: ', intercept_dict.get(state)[0])
    print('95% CI: ', ci_slope_dict.get(state)[0])
    print('R Squared: ', r_squared_dict.get(state)[0])
    print('P-Value: ', p_value_dict.get(state)[0])
    print('_______________________________________')
    print('')
    if p_value_dict.get(state)[0] < 0.05:
        significant.append(state)
    else:
        insignificant.append(state)

STATE:  Alabama
Baseline:  265917
2021-22:  239392
Total Change %:  [np.float64(-9.974916985375136)]
Avg Change %:  -1.1460086297790484
Slope:  -0.9769282076054494
Intercept:  100.26594080791443
95% CI:  (np.float64(-1.3821679751514382), np.float64(-0.5716884400594606))
R Squared:  0.7880255359690876
P-Value:  0.0006062015452915853
_______________________________________

STATE:  Alaska
Baseline:  30018
2021-22:  18943
Total Change %:  [np.float64(-36.894529948697446)]
Avg Change %:  -4.862862039150015
Slope:  -5.122542636034542
Intercept:  108.68872615824444
95% CI:  (np.float64(-6.226079005115164), np.float64(-4.0190062669539195))
R Squared:  0.9323561356925458
P-Value:  5.886735958030527e-06
_______________________________________

STATE:  Arizona
Baseline:  621610
2021-22:  501925
Total Change %:  [np.float64(-19.25403387976384)]
Avg Change %:  -2.291436690024194
Slope:  -2.1266457142327866
Intercept:  94.69002926418348
95% CI:  (np.float64(-3.0821704103354923), np.float64(-1.1711210181300808))
R Squared:  0.7601090417724562
P-Value:  0.0010082146779202795
_______________________________________

STATE:  Arkansas
Baseline:  157504
2021-22:  125965
Total Change %:  [np.float64(-20.024253352295815)]
Avg Change %:  -2.43755971615008
Slope:  -2.1318785169861965
Intercept:  100.51533467548298
95% CI:  (np.float64(-2.4451797831928834), np.float64(-1.8185772507795095))
R Squared:  0.9673395054317669
P-Value:  3.152848568569703e-07
_______________________________________

STATE:  California
Baseline:  2359659
2021-22:  2161195
Total Change %:  [np.float64(-8.410706801279337)]
Avg Change %:  -0.9402894143245527
Slope:  -0.6687666362475311
Intercept:  103.26779651404946
95% CI:  (np.float64(-1.4674213212871698), np.float64(0.1298880487921077))
R Squared:  0.30964257555949304
P-Value:  0.09480297722891091
_______________________________________

STATE:  Colorado
Baseline:  305234
2021-22:  285300
Total Change %:  [np.float64(-6.530727245326537)]
Avg Change %:  -0.7267447161667223
Slope:  -0.2244477709203142
Intercept:  98.31228142700651
95% CI:  (np.float64(-0.7529018531721564), np.float64(0.304006311331528))
R Squared:  0.10345334443575879
P-Value:  0.36479090395081787
_______________________________________

STATE:  Connecticut
Baseline:  166812
2021-22:  146651
Total Change %:  [np.float64(-12.086060954847373)]
Avg Change %:  -1.4119321123244568
Slope:  -1.267196822552552
Intercept:  101.42949166508623
95% CI:  (np.float64(-1.6399838800209212), np.float64(-0.8944097650841829))
R Squared:  0.8808292510872027
P-Value:  5.7991890361726134e-05
_______________________________________

STATE:  Delaware
Baseline:  47816
2021-22:  45589
Total Change %:  [np.float64(-4.657436841224695)]
Avg Change %:  -0.5089494753807463
Slope:  -0.1838360178664677
Intercept:  101.75414847825756
95% CI:  (np.float64(-0.7853547075176643), np.float64(0.417682671784729))
R Squared:  0.056378846489027815
P-Value:  0.5089011389910075
_______________________________________

STATE:  District of Columbia
Baseline:  47699
2021-22:  53434
Total Change %:  [np.float64(12.023312857711902)]
Avg Change %:  1.3023837540915677
Slope:  1.5156406938205302
Intercept:  98.89126701722354
95% CI:  (np.float64(1.0704087558097537), np.float64(1.9608726318313068))
R Squared:  0.8811318642692294
P-Value:  5.739735563044365e-05
_______________________________________

STATE:  Florida
Baseline:  1023813
2021-22:  870188
Total Change %:  [np.float64(-15.005181610313603)]
Avg Change %:  -1.7786345129720955
Slope:  -1.393361696112296
Intercept:  99.1174933135428
95% CI:  (np.float64(-1.7404523737679494), np.float64(-1.0462710184566428))
R Squared:  0.9115712990249462
P-Value:  1.7346103844377622e-05
_______________________________________

STATE:  Georgia
Baseline:  476813
2021-22:  450908
Total Change %:  [np.float64(-5.432947507723154)]
Avg Change %:  -0.6098393051198734
Slope:  -0.25697387623341783
Intercept:  98.02161053037182
95% CI:  (np.float64(-0.605823906240907), np.float64(0.09187615377407132))
R Squared:  0.25766521596764896
P-Value:  0.13419945867458222
_______________________________________

STATE:  Hawaii
Baseline:  69272
2021-22:  53343
Total Change %:  [np.float64(-22.994860838434)]
Avg Change %:  -2.8467080601183734
Slope:  -2.7969147532607512
Intercept:  98.41155812659451
95% CI:  (np.float64(-3.3745769178783878), np.float64(-2.2192525886431147))
R Squared:  0.9374831217948448
P-Value:  4.2855555432460574e-06
_______________________________________

STATE:  Idaho
Baseline:  99901
2021-22:  117204
Total Change %:  [np.float64(17.320146945476022)]
Avg Change %:  1.8894623274861122
Slope:  1.6604377727889996
Intercept:  105.04672352902101
95% CI:  (np.float64(0.33363020020129386), np.float64(2.9872453453767056))
R Squared:  0.5004518172304219
P-Value:  0.022116683529781748
_______________________________________

STATE:  Illinois
Baseline:  713711
2021-22:  516121
Total Change %:  [np.float64(-27.684875250626657)]
Avg Change %:  -3.526971652769573
Slope:  -3.166789817268793
Intercept:  100.54269483408169
95% CI:  (np.float64(-3.3528628896191606), np.float64(-2.9807167449184258))
R Squared:  0.9946317180120395
P-Value:  2.275799814296094e-10
_______________________________________

STATE:  Indiana
Baseline:  392625
2021-22:  355552
Total Change %:  [np.float64(-9.442343202801656)]
Avg Change %:  -1.0124308980066639
Slope:  -1.4916708633614084
Intercept:  98.6459668316402
95% CI:  (np.float64(-2.370013235560669), np.float64(-0.6133284911621477))
R Squared:  0.6484943605825914
P-Value:  0.004934746610632122
_______________________________________

STATE:  Iowa
Baseline:  315418
2021-22:  174948
Total Change %:  [np.float64(-44.53455414719515)]
Avg Change %:  -6.198449543435108
Slope:  -4.589221383380245
Intercept:  93.77100747694689
95% CI:  (np.float64(-5.702268302907378), np.float64(-3.476174463853112))
R Squared:  0.915785454869371
P-Value:  1.4242530791902246e-05
_______________________________________

STATE:  Kansas
Baseline:  187868
2021-22:  165451
Total Change %:  [np.float64(-11.932314178039901)]
Avg Change %:  -1.343490650139988
Slope:  -1.5769195779628642
Intercept:  104.77669040351348
95% CI:  (np.float64(-2.4224807915463584), np.float64(-0.7313583643793697))
R Squared:  0.6899000817833567
P-Value:  0.002920662323223588
_______________________________________

STATE:  Kentucky
Baseline:  245942
2021-22:  200323
Total Change %:  [np.float64(-18.54868220962666)]
Avg Change %:  -2.2428820662501217
Slope:  -1.8440957870579484
Intercept:  97.57167432676292
95% CI:  (np.float64(-2.2618559188561944), np.float64(-1.4263356552597024))
R Squared:  0.9257296225041753
P-Value:  8.579236896866009e-06
_______________________________________

STATE:  Louisiana
Baseline:  227269
2021-22:  202107
Total Change %:  [np.float64(-11.071461571969781)]
Avg Change %:  -1.2894349438981847
Slope:  -1.0427984352276713
Intercept:  98.03180772164663
95% CI:  (np.float64(-1.3209545508328349), np.float64(-0.764642319622508))
R Squared:  0.8999039206982652
P-Value:  2.8622082483138932e-05
_______________________________________

STATE:  Maine
Baseline:  63084
2021-22:  59230
Total Change %:  [np.float64(-6.1093145647073746)]
Avg Change %:  -0.6901813362765556
Slope:  -0.47745862659311433
Intercept:  100.12522985226047
95% CI:  (np.float64(-0.7827219178195437), np.float64(-0.17219533536668502))
R Squared:  0.6101164843905637
P-Value:  0.007639774249956775
_______________________________________

STATE:  Maryland
Baseline:  302485
2021-22:  260297
Total Change %:  [np.float64(-13.947137874605353)]
Avg Change %:  -1.638868118148858
Slope:  -1.1895165350047405
Intercept:  100.59470417015419
95% CI:  (np.float64(-1.672625060122939), np.float64(-0.706408009886542))
R Squared:  0.7949976950778754
P-Value:  0.0005284980156326627
_______________________________________

STATE:  Massachusetts
Baseline:  381832
2021-22:  327318
Total Change %:  [np.float64(-14.276959500513314)]
Avg Change %:  -1.6865322918061507
Slope:  -1.6626715731557653
Intercept:  102.0204840205783
95% CI:  (np.float64(-2.0394842896282936), np.float64(-1.285858856683237))
R Squared:  0.9256740156325524
P-Value:  8.605163497402521e-06
_______________________________________

STATE:  Michigan
Baseline:  575510
2021-22:  407778
Total Change %:  [np.float64(-29.144932320897986)]
Avg Change %:  -3.744583456556216
Slope:  -3.3045620142977277
Intercept:  99.8588003367764
95% CI:  (np.float64(-3.480546152855064), np.float64(-3.1285778757403913))
R Squared:  0.9955858974827178
P-Value:  1.0399105561257981e-10
_______________________________________

STATE:  Minnesota
Baseline:  335747
2021-22:  270367
Total Change %:  [np.float64(-19.472996035705457)]
Avg Change %:  -2.3743604793562736
Slope:  -1.9801417932748966
Intercept:  99.07007359708352
95% CI:  (np.float64(-2.1662959584005037), np.float64(-1.7939876281492897))
R Squared:  0.9863718147630445
P-Value:  9.483998309164766e-09
_______________________________________

STATE:  Mississippi
Baseline:  155386
2021-22:  134267
Total Change %:  [np.float64(-13.591314532840796)]
Avg Change %:  -1.593909597679414
Slope:  -1.1744827836367615
Intercept:  100.6753621187354
95% CI:  (np.float64(-1.748645938835082), np.float64(-0.6003196284384411))
R Squared:  0.7280071840336603
P-Value:  0.0016938477253745695
_______________________________________

STATE:  Missouri
Baseline:  363308
2021-22:  262407
Total Change %:  [np.float64(-27.772853887060016)]
Avg Change %:  -3.5369766383138295
Slope:  -3.2228785927025436
Intercept:  101.09837683428135
95% CI:  (np.float64(-3.44484258805216), np.float64(-3.0009145973529274))
R Squared:  0.9926394015786437
P-Value:  8.049951351015338e-10
_______________________________________

STATE:  Montana
Baseline:  48424
2021-22:  40901
Total Change %:  [np.float64(-15.535684784404427)]
Avg Change %:  -1.8278260812683247
Slope:  -1.967431626691497
Intercept:  101.17605094393464
95% CI:  (np.float64(-2.3851050910534997), np.float64(-1.5497581623294947))
R Squared:  0.9341811895370623
P-Value:  5.27260067189335e-06
_______________________________________

STATE:  Nebraska
Baseline:  115721
2021-22:  108474
Total Change %:  [np.float64(-6.262476127928379)]
Avg Change %:  -0.7119604771811456
Slope:  -0.5357347203684509
Intercept:  98.1345728872971
95% CI:  (np.float64(-0.7921816824477291), np.float64(-0.27928775828917274))
R Squared:  0.7362621578448799
P-Value:  0.0014909806906834944
_______________________________________

STATE:  Nevada
Baseline:  106854
2021-22:  102771
Total Change %:  [np.float64(-3.821101690156662)]
Avg Change %:  -0.4155732251298727
Slope:  -0.23471278567016507
Intercept:  99.95002526812286
95% CI:  (np.float64(-0.5768816451812142), np.float64(0.10745607384088401))
R Squared:  0.2313529564237397
P-Value:  0.1593246289781903
_______________________________________

STATE:  New Hampshire
Baseline:  66770
2021-22:  163391
Total Change %:  [np.float64(144.70720383405722)]
Avg Change %:  10.514960122757795
Slope:  16.603854933943296
Intercept:  94.629515160592
95% CI:  (np.float64(15.75607165425501), np.float64(17.451638213631583))
R Squared:  0.9959408991711105
P-Value:  7.435048224608038e-11
_______________________________________

STATE:  New Jersey
Baseline:  376901
2021-22:  314658
Total Change %:  [np.float64(-16.51441625254377)]
Avg Change %:  -1.9653238426391526
Slope:  -1.655377229918024
Intercept:  101.3659820483363
95% CI:  (np.float64(-2.115678542758739), np.float64(-1.1950759170773093))
R Squared:  0.8921604917577629
P-Value:  3.869195168866602e-05
_______________________________________

STATE:  New Mexico
Baseline:  141773
2021-22:  92574
Total Change %:  [np.float64(-34.70265847516805)]
Avg Change %:  -4.5818912137458305
Slope:  -3.883980986250107
Intercept:  100.78051789576551
95% CI:  (np.float64(-4.252157323947731), np.float64(-3.5158046485524825))
R Squared:  0.9861470056991739
P-Value:  1.0126363042697428e-08
_______________________________________

STATE:  New York
Baseline:  1071051
2021-22:  895620
Total Change %:  [np.float64(-16.3793320766238)]
Avg Change %:  -1.9551026507348424
Slope:  -1.6969511368937737
Intercept:  102.17530766933177
95% CI:  (np.float64(-2.1650593665324385), np.float64(-1.2288429072551088))
R Squared:  0.8936875722612723
P-Value:  3.652188931554658e-05
_______________________________________

STATE:  North Carolina
Baseline:  508270
2021-22:  474251
Total Change %:  [np.float64(-6.693096189033387)]
Avg Change %:  -0.7621932547809789
Slope:  -0.6026300743281873
Intercept:  99.41447369597762
95% CI:  (np.float64(-0.8174830626293934), np.float64(-0.3877770860269811))
R Squared:  0.834228248977911
P-Value:  0.00022179384163450617
_______________________________________

STATE:  North Dakota
Baseline:  48123
2021-22:  42490
Total Change %:  [np.float64(-11.705421524011388)]
Avg Change %:  -1.3690927385786997
Slope:  -1.2180151996871658
Intercept:  100.53748632764903
95% CI:  (np.float64(-1.5025261469991191), np.float64(-0.9335042523752125))
R Squared:  0.9214062284987357
P-Value:  1.0778095591524121e-05
_______________________________________

STATE:  Ohio
Baseline:  618887
2021-22:  558738
Total Change %:  [np.float64(-9.718898603460728)]
Avg Change %:  -1.1190584259131504
Slope:  -0.9481664323016624
Intercept:  97.58722586602312
95% CI:  (np.float64(-1.4305040249608738), np.float64(-0.4658288396424509))
R Squared:  0.7119693013856511
P-Value:  0.002148169108868194
_______________________________________

STATE:  Oklahoma
Baseline:  202064
2021-22:  156081
Total Change %:  [np.float64(-22.75665135798559)]
Avg Change %:  -2.825139441612086
Slope:  -2.3917714639466174
Intercept:  99.30155342321785
95% CI:  (np.float64(-2.531645768433784), np.float64(-2.251897159459451))
R Squared:  0.9946817943408062
P-Value:  2.1920201783803043e-10
_______________________________________

STATE:  Oregon
Baseline:  225194
2021-22:  167620
Total Change %:  [np.float64(-25.566400525768895)]
Avg Change %:  -3.195507481826343
Slope:  -2.5705297600641175
Intercept:  100.28884186321773
95% CI:  (np.float64(-3.072972332299099), np.float64(-2.068087187829136))
R Squared:  0.943639095712274
P-Value:  2.8236013380635147e-06
_______________________________________

STATE:  Pennsylvania
Baseline:  640348
2021-22:  501041
Total Change %:  [np.float64(-21.754889528818705)]
Avg Change %:  -2.6828828034626038
Slope:  -2.3479496281472705
Intercept:  100.68297522313152
95% CI:  (np.float64(-2.540660491745941), np.float64(-2.1552387645485998))
R Squared:  0.9895785165962065
P-Value:  3.2388788587763945e-09
_______________________________________

STATE:  Rhode Island
Baseline:  73338
2021-22:  63104
Total Change %:  [np.float64(-13.954566527584609)]
Avg Change %:  -1.6413865311889064
Slope:  -1.4737574551040968
Intercept:  102.44744755912227
95% CI:  (np.float64(-1.9760071339069594), np.float64(-0.9715077763012343))
R Squared:  0.8463352739621707
P-Value:  0.0001628427259205146
_______________________________________

STATE:  South Carolina
Baseline:  233835
2021-22:  204663
Total Change %:  [np.float64(-12.47546346782988)]
Avg Change %:  -1.4624360372196572
Slope:  -1.4325356328050527
Intercept:  100.36015294389789
95% CI:  (np.float64(-1.5980850350673244), np.float64(-1.266986230542781))
R Squared:  0.9795489804962919
P-Value:  4.8228292653739215e-08
_______________________________________

STATE:  South Dakota
Baseline:  49259
2021-22:  43658
Total Change %:  [np.float64(-11.370510972614142)]
Avg Change %:  -1.3268313968893275
Slope:  -1.1502835660857555
Intercept:  99.36495222838835
95% CI:  (np.float64(-1.403016173914705), np.float64(-0.8975509582568062))
R Squared:  0.9298286113127173
P-Value:  6.824450095428827e-06
_______________________________________

STATE:  Tennessee
Baseline:  295289
2021-22:  254568
Total Change %:  [np.float64(-13.79021907351781)]
Avg Change %:  -1.6245607426438622
Slope:  -1.2135024988873262
Intercept:  98.87782046494358
95% CI:  (np.float64(-1.5773724800699416), np.float64(-0.8496325177047108))
R Squared:  0.8767638355052177
P-Value:  6.643990600843256e-05
_______________________________________

STATE:  Texas
Baseline:  1362852
2021-22:  1358538
Total Change %:  [np.float64(-0.31654207500154086)]
Avg Change %:  -0.0132757774881432
Slope:  0.4109310341975363
Intercept:  100.88176719248912
95% CI:  (np.float64(-0.27520445408953076), np.float64(1.0970665224846035))
R Squared:  0.18662313971912148
P-Value:  0.2124905607334098
_______________________________________

STATE:  Utah
Baseline:  239025
2021-22:  327718
Total Change %:  [np.float64(37.106160443468255)]
Avg Change %:  3.617662339069909
Slope:  5.219142158960169
Intercept:  94.97954379058866
95% CI:  (np.float64(4.29991310670298), np.float64(6.1383712112173585))
R Squared:  0.9537483257554142
P-Value:  1.2751609861127325e-06
_______________________________________

STATE:  Vermont
Baseline:  37798
2021-22:  34307
Total Change %:  [np.float64(-9.235938409439653)]
Avg Change %:  -1.0497001398731207
Slope:  -1.1142645033327079
Intercept:  101.37881273179438
95% CI:  (np.float64(-1.6637799671027285), np.float64(-0.5647490395626872))
R Squared:  0.7245255202711582
P-Value:  0.0017855040994751506
_______________________________________

STATE:  Virginia
Baseline:  492552
2021-22:  426852
Total Change %:  [np.float64(-13.338693173512645)]
Avg Change %:  -1.5751533059972063
Slope:  -1.4290544680838495
Intercept:  100.31971520496592
95% CI:  (np.float64(-1.5699797737977177), np.float64(-1.2881291623699813))
R Squared:  0.9850248210837154
P-Value:  1.3834526930783418e-08
_______________________________________

STATE:  Washington
Baseline:  329617
2021-22:  282065
Total Change %:  [np.float64(-14.426440383839426)]
Avg Change %:  -1.6662387695099423
Slope:  -1.2258322583942922
Intercept:  102.8601624971351
95% CI:  (np.float64(-2.2088327361117104), np.float64(-0.24283178067687416))
R Squared:  0.4986818854616106
P-Value:  0.02245993958059187
_______________________________________

STATE:  West Virginia
Baseline:  136155
2021-22:  110322
Total Change %:  [np.float64(-18.97322904043186)]
Avg Change %:  -2.301604661680384
Slope:  -2.0458768582598044
Intercept:  100.00795884369752
95% CI:  (np.float64(-2.2885711820043553), np.float64(-1.8031825345152532))
R Squared:  0.978474453409461
P-Value:  5.9217333277854193e-08
_______________________________________

STATE:  Wisconsin
Baseline:  329773
2021-22:  274617
Total Change %:  [np.float64(-16.72544447240981)]
Avg Change %:  -2.005404995824031
Slope:  -1.7899052507101074
Intercept:  99.98244522471795
95% CI:  (np.float64(-2.01700262944665), np.float64(-1.5628078719735647))
R Squared:  0.9754520889714039
P-Value:  1.0028264693560893e-07
_______________________________________

STATE:  Wyoming
Baseline:  35103
2021-22:  27837
Total Change %:  [np.float64(-20.69908554824374)]
Avg Change %:  -2.5322259600598254
Slope:  -2.1813382090281506
Intercept:  98.51812717379764
95% CI:  (np.float64(-2.567600452921798), np.float64(-1.7950759651345032))
R Squared:  0.953271734638342
P-Value:  1.3288012444264541e-06
_______________________________________

In [217]:
print('Significant: ', significant)
print('Not Significant: ', insignificant)

Significant:  ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'Connecticut', 'District of Columbia', 'Florida', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
Not Significant:  ['California', 'Colorado', 'Delaware', 'Georgia', 'Nevada', 'Texas']

The states that show not statistically significant declining trend are ['California', 'Colorado', 'Delaware', 'Georgia', 'Nevada', 'Texas']. This as to do with their p value being greater than 0.05.

In [219]:
for state in significant:
    if slope_dict.get(state)[0] > 0:
        print(state + ': ', slope_dict.get(state)[0])

District of Columbia:  1.5156406938205302
Idaho:  1.6604377727889996
New Hampshire:  16.603854933943296
Utah:  5.219142158960169

Of the states with significant trends, only 4 have a positive trend, being D.C., Idaho, New Hampshire and Utah.

#### Visualization

In [221]:
## Positive Enrollment Trend
fig = go.Figure()

for state in ['District of Columbia', 'Idaho', 'New Hampshire', 'Utah']:
    fig.add_trace(go.Scatter(x=state_trends[state_trends['State'] == state]['Year'], y=state_trends[state_trends['State'] == state]['enrollment_index'], mode='lines', name=state))

fig.update_layout(title='Enrollment Index Over Time', xaxis_title='Year', yaxis_title='Total Enrollment')
fig.show()

In [223]:
## Negative Enrollment Trend
fig = go.Figure()

for state in states:
    if state not in ['District of Columbia', 'Idaho', 'New Hampshire', 'Utah']:
        fig.add_trace(go.Scatter(x=state_trends[state_trends['State'] == state]['Year'], y=state_trends[state_trends['State'] == state]['enrollment_index'], mode='lines', name=state))

fig.update_layout(title='Enrollment Index Over Time', xaxis_title='Year', yaxis_title='Total Enrollment')
fig.show()

In [224]:
## Not Significant Trends
fig = go.Figure()

for state in insignificant:
    fig.add_trace(go.Scatter(x=state_trends[state_trends['State'] == state]['Year'], y=state_trends[state_trends['State'] == state]['enrollment_index'], mode='lines', name=state))

fig.update_layout(title='Enrollment Index Over Time', xaxis_title='Year', yaxis_title='Total Enrollment')
fig.show()

**Question** which states have statistically significant declining trends?

**Answer** 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'Connecticut', 'Florida', 'Hawaii', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'

These states have statistically significant negative trends making them definitively decreasing for a cause other than randomness.

---------

**sub-question** Which states show statistically significant growth trends?

Using the Mann-Kendall test for this

----

**sub-question** What is the effect size of enrollment changes (Cohen's d)?

------

**sub-question** Are there inflection points where enrollment trends shifted direction?

-----